apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hello
spec:
  ingressClassName: nginx
  rules:
  - host: "hello.chalam-kitchen.com"
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/hello"
        backend:
          service:
            name: hello-service
            port:
              number: 80
